{{- if .Values.rems.theme.create }}
apiVersion: v1
data:
{{- $filename := printf "files/theme/%s" (.Values.rems.theme.filename) -}}
{{- $theme := .Files.Glob $filename }}
{{ ($theme).AsConfig | indent 2 }}
kind: ConfigMap
metadata:
  name:  {{ .Values.name }}-theme
{{- end }}
