# Default values for REMS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
postgres:
  create: true
  pvc: false
  storage: "1Gi"
db:
  name: "rems"
  hostname: "postgres-rems"
  port: 5432
  wait: true
  user: "rems"
  password: "rems"
  addData: true
  addDataType: "test-data"

image:
  name: cscfi/rems
  tag: latest
  pullPolicy: IfNotPresent #Always

hostname: rems.fi
protocol: http
port: 3001
extraCommands: ""
run: true
migrate: true
ingress:
  create: true
  path: ""

customConfig: false
theme:
  create: true
extrapages:
  create: true
certs:
  create: false
