# Default values for REMS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
postgres:
  create: true
  pvc: false
  storage: "1Gi"
dbConnection:
  name: "rems"
  hostname: "postgres-rems"
  port: 5432
  wait: true
  user: "rems"
  password: "rems"
  addData: false
  addDataType: "test-data"

image:
  name: cscfi/rems
  tag: release
  pullPolicy: IfNotPresent #Always

orchestrator: kubernetes
readOnlyFilesystem: false
hostname: rems.localhost
name: rems
protocol: http
port: 3001
extraCommands: ""
run: true
migrate: true
ingress:
  create: true
  path: ""

customConfig: false
theme:
  create: false
extrapages:
  create: false
certs:
  create: false
keys:
  create: false
