# Default values for REMS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#############
## GENERAL ##
#############
name: rems
orchestrator: openshift # kubernetes or openshift
hostname: "" # Set a hostname (REQUIRED)
readOnlyFilesystem: false
protocol: http
port: 3001
extraCommands: ""
run: true
migrate: true

# If orchestrator is kubernetes
ingress:
  create: true
  path: ""

################
## POSTGRESQL ##
################
postgresql:
  enabled: true

  auth:
    enablePostgresUser: false
    username: # Set an username (REQUIRED)
    password: # Set a password (REQUIRED)
    database: rems

  tls:
    enabled: false
  
  # SecurityContext disabled by default for OpenShift.
  primary:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false

  readReplicas:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  
  backup:
    cronjob:
      podSecurityContext:
        enabled: false
      containerSecurityContext:
        enabled: false
  
  metrics:
    containerSecurityContext:
      enabled: false

##########
## REMS ##
##########
image:
  name: cscfi/rems
  tag: latest
  pullPolicy: IfNotPresent

database:
  addData: false
  addDataType: "test-data"
  wait: true

customConfig: false
theme:
  create: true
  filename: "theme.edn"
extrapages:
  create: true
  filename: "about-en.md"
certs:
  create: true
keys:
  create: true
