# Default values for REMS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
postgres:
  create: true
  pvc: false
  storage: 8Gi

  image:
    name: image-registry.openshift-image-registry.svc:5000/openshift/postgresql
    tag: 13-el7
    pullPolicy: IfNotPresent

  dbConnection:
    name: "rems"
    hostname: "postgres-rems"
    port: 5432
    wait: true
    user: "rems"
    password: "rems"
    addData: false
    addDataType: "test-data"
    tls: false

image:
  rems:
    name: cscfi/rems
    tag: latest
    pullPolicy: IfNotPresent

orchestrator: openshift
readOnlyFilesystem: false
hostname: "rems.apps.okd.lumi-k.csc.fi"
name: rems
protocol: http
port: 3001
extraCommands: ""
run: true
migrate: true
ingress:
  create: true
  path: ""

customConfig: false
theme:
  create: true
extrapages:
  create: true
certs:
  create: true
keys:
  create: true
