{{- if .Values.postgres.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name | default "postgres-rems" }}
  labels:
    app: {{ .Values.postgres.name | default "postgres-rems" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name | default "postgres-rems" }}
  template:
    metadata:
      name: {{ .Values.postgres.name | default "postgres-rems" }}
      labels:
        app: {{ .Values.postgres.name | default "postgres-rems" }}
    spec:
      {{- if .Values.readOnlyFilesystem }}
      serviceAccountName: postgres-rems
      {{- end }}
      {{- if eq .Values.orchestrator "kubernetes" }}
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      {{- end }}
      containers:
        - name: postgres-rems
          image: {{ .Values.postgres.image.name }}:{{ .Values.postgres.image.tag }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.dbConnection.port | default 5432 }}
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.postgres.dbConnection.password | default "rems" | quote }}
            - name: POSTGRESQL_PASSWORD
              value: {{ required "A valid .Values.postgres.password entry required!" .Values.postgres.dbConnection.password }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgres.dbConnection.name | default "rems" | quote }}
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: data
      volumes:
        - name: data
      {{- if .Values.postgres.pvc }}
          persistentVolumeClaim:
            claimName: postgres-rems
      {{- else }}
          emptyDir: {}
      {{- end }}
{{- end }}
