apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.postgres.name | default "postgres-rems" }}
  name: {{ .Values.postgres.hostname | default "postgres-rems" }}
spec:
  selector:
    app: {{ .Values.postgres.name | default "postgres-rems" }}
  ports:
  - name: sql
    protocol: TCP
    port: {{ .Values.postgres.port | default "5432" }}
