{{- if .Values.postgres.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name | default "postgres-rems" }}
  labels:
    app: {{ .Values.postgres.name | default "postgres-rems" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.name | default "postgres-rems" }}
  template:
    metadata:
      name: {{ .Values.postgres.name | default "postgres-rems" }}
      labels:
        app: {{ .Values.postgres.name | default "postgres-rems" }}
    spec:
    {{- if .Values.readOnlyFilesystem }}
      serviceAccountName: postgres-rems
    {{- end }}
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
        - name: {{ .Values.postgres.name | default "postgres-rems" }}
          image: {{ include "imageRegistry" . }}postgres:13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.dbConnection.port | default 5432 }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.dbConnection.password | default "rems" | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ required "A valid .Values.postgres.password entry required!" .Values.dbConnection.password }}
            - name: POSTGRES_DATABASE
              value: {{ .Values.dbConnection.name | default "rems" | quote }}
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: data
      volumes:
        - name: data
      {{- if .Values.postgres.pvc }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.name | default "postgres-rems" }}
      {{- else }}
          emptyDir: {}
      {{- end }}
{{- end }}
