{{- if and (and (.Values.ingress.create) (eq .Values.orchestrator "kubernetes")) (eq .Values.protocol "https") }}
apiVersion: v1
data:
  {{- (.Files.Glob "files/tls/**").AsSecrets | nindent 2 }}
kind: Secret
metadata:
  name:  {{ .Values.name }}-tls
type: kubernetes.io/tls
{{- end }}
