---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default "rems" }}
  labels:
    app: {{ .Values.name | default "rems" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name | default "rems" }}
  template:
    metadata:
      name: {{ .Values.name | default "rems" }}
      labels:
        app: {{ .Values.name | default "rems" }}
    spec:
      initContainers:
      {{- if .Values.dbConnection.wait }}
      - name: database-wait
        image: {{ include "imageRegistry" . }}postgres:13
        imagePullPolicy: "IfNotPresent"
        command:
        - sh
        - -c
        - |
          until timeout 1 psql -v ON_ERROR_STOP=1 \
                               -h {{ .Values.dbConnection.hostname }} \
                               -U {{ .Values.dbConnection.user }} \
                               -d {{ .Values.dbConnection.name }} \
                               -c "SELECT 1" -w 1> /dev/null
          do
            echo "Waiting for database to accept connections"
            sleep 2
          done
          echo "Database connection found"
        env:
        - name: PGPASSWORD
          value: {{ .Values.dbConnection.password | quote }}
      {{- end }}
      {{- if .Values.migrate }}
      - name: database-migrate
        image: {{ include "imageRegistry" . }}{{ .Values.image.name | default "cscfi/rems" }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" | quote }}
        env:
        - name: COMMANDS
          value: "migrate"
        - name: CMD
          value: "migrate"
        volumeMounts:
        - name: init-config
          mountPath: /rems/config
      {{- end }}
      {{- if .Values.dbConnection.addData }}
      - name: database-add-data
        image: {{ include "imageRegistry" . }}{{ .Values.image.name | default "cscfi/rems" }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" | quote }}
        env:
        - name: COMMANDS
          value: {{ .Values.dbConnection.addDataType | default "test-data" | quote }}
        - name: CMD
          value: {{ .Values.dbConnection.addDataType | default "test-data" | quote }}
        volumeMounts:
        - name: init-config
          mountPath: /rems/config
      {{- end }}
      {{- if .Values.extraCommands }}
      - name: extra-commands
        image: {{ include "imageRegistry" . }}{{ .Values.image.name | default "cscfi/rems" }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" | quote }}
        env:
        - name: CMD
          value: {{ .Values.extraCommands | quote }}
        volumeMounts:
        - name: init-config
          mountPath: /rems/config
      {{- end }}
      containers:
      - name: {{ .Values.name | default "rems" }}
        image: {{ include "imageRegistry" . }}{{ .Values.image.name | default "cscfi/rems" }}:{{ .Values.image.tag | default "latest" }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" | quote }}
        {{- if not (.Values.run) }}
        command: ["sh", "-c", "exit 0"]
        {{- end }}
        ports:
        - containerPort: {{ .Values.port | default "3001" }}
          name: rems
        volumeMounts:
        - name: config
          mountPath: /rems/config
        {{- $img := .Files.Glob "files/img/*" }}
        {{- $trans := .Files.Glob "files/extra-translations/*" }}
        {{- $keys := .Files.Glob "files/keys/*" }}
        {{- $db_tls := .Files.Glob "files/db-tls/*" }}
        {{- if .Values.theme.create }}
        - name: theme
          mountPath: /rems/theme
          {{- if $img }}
        - name: img
          mountPath: /rems/theme/public/img
          {{- end }}
          {{- if $trans }}
        - name: extra-translations
          mountPath: /rems/theme/extra-translations
          {{- end }}
        {{- end }}
        {{- if .Values.extrapages.create }}
        - name: extra-pages
          mountPath: /rems/extra-pages
        {{- end }}
        {{- if .Values.certs.create }}
        - name: certs
          mountPath: /rems/certs
        {{- end }}
        {{- if $keys }}
        - name: keys
          mountPath: /rems/keys
        {{- end }}
        {{- if $db_tls }}
          {{- if .Values.dbConnection.tls }}
        - name: db-tls
          mountPath: /rems/db-tls
          {{- end }}
        {{- end }}
        {{- if .Values.readOnlyFilesystem }}
        - name: tmp
          mountPath: /tmp
        {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ .Values.name | default "rems" }}-config
      - name: init-config
        configMap:
          name: {{ .Values.name | default "rems" }}-init-config
      {{- if .Values.theme.create }}
      - name: theme
        configMap:
          name:  {{ .Values.name | default "rems" }}-theme
        {{- if $img }}
      - name: img
        configMap:
          name: {{ .Values.name | default "rems" }}-img
        {{- end }}
        {{- if $trans  }}
      - name: extra-translations
        configMap:
          name: {{ .Values.name | default "rems" }}-extra-translations
        {{- end }}
      {{- end }}
      {{- if .Values.extrapages.create }}
      - name: extra-pages
        configMap:
          name: {{ .Values.name | default "rems" }}-extra-pages
      {{- end }}
      {{- if .Values.certs.create }}
      - name: certs
        configMap:
          name: {{ .Values.name | default "rems" }}-certs
      {{- end }}
      {{- if $keys }}
      - name: keys
        secret:
          secretName: {{ .Values.name | default "rems" }}-keys
      {{- end }}
      {{- if $db_tls }}
      - name: db-tls
        secret:
          secretName: {{ .Values.name | default "rems" }}-db-tls
      {{- end }}
      {{- if .Values.readOnlyFilesystem }}
      - name: tmp
        emptyDir: {}
      {{- end }}
