apiVersion: v1
data:
  config.edn: |-
    {:port {{ .Values.port | default 3001 }}
     :database-url "postgresql://{{ .Values.postgres.dbConnection.hostname | default "postgres-rems" }}:{{ .Values.postgres.dbConnection.port }}/{{ .Values.postgres.dbConnection.name | default "rems" }}?user={{ .Values.postgres.dbConnection.user | default "rems" }}&password={{ required "A valid .Values.postgres.dbConnection.password entry required!" .Values.postgres.dbConnection.password }}"
     :search-index-path "/tmp/rems-search-index"
     :authentication :fake
     :public-url "{{ .Values.protocol }}://{{ required "A valid .Values.hostname entry required!" .Values.hostname }}/"}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.name | default "rems" }}-init-config
