---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default "rems" }}
  labels:
    app: {{ .Values.name | default "rems" }}
spec:
  ports:
  - port: {{ .Values.port | default "3001" }}
    protocol: TCP
    targetPort: {{ .Values.port | default "3001" }}
  selector:
    app: {{ .Values.name | default "rems" }}
  sessionAffinity: None
  type: ClusterIP
