apiVersion: v1
data:
  config.edn: |-
    {:port {{ .Values.port }}
     :database-url "postgresql://rems-postgresql:5432/{{ .Values.postgresql.auth.database }}?user={{ .Values.postgresql.auth.username }}&password={{ required "A valid .Values.postgresql.auth.password entry required!" .Values.postgresql.auth.password }}"
     :search-index-path "/tmp/rems-search-index"
     :authentication :fake
     :public-url "{{ .Values.protocol }}://{{ .Values.name }}.{{ required "A valid .Values.hostname entry required!" .Values.hostname }}/"}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{ .Values.name }}-init-config
