{{- if .Values.extrapages.create }}
apiVersion: v1
data:
  {{- (.Files.Glob "files/extra-pages/**.md").AsConfig | nindent 2 }}
kind: ConfigMap
metadata:
  name:  {{ .Values.name }}-extra-pages
{{- end }}
