{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name | default "rems" }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: /{{ .Values.ingress.path | default "" }}
        backend:
          serviceName: {{ .Values.name | default "rems" }}
          servicePort: {{ .Values.port | default "3001" }}
{{- end }}
