{{- if or (and (and (.Values.ingress.create) (eq .Values.orchestrator "kubernetes")) (eq .Values.protocol "https")) (.Values.dbConnection.tls) }}
apiVersion: v1
data:
  {{- (.Files.Glob "files/tls/**").AsSecrets | nindent 2 }}
kind: Secret
metadata:
  name:  {{ .Values.name | default "rems" }}-tls
type: kubernetes.io/tls
{{- end }}
