{{- if .Values.ingress.create }}
{{- if eq .Values.orchestrator "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ .Values.name | default "rems" }}
  name: {{ .Values.name | default "rems" }}
spec:
  host: {{ .Values.hostname }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Values.name | default "rems" }}
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - host: {{ .Values.hostname }}
    routerName: router
    wildcardPolicy: None
{{- end }}
{{- end }}
