{{- if .Values.extrapages.create }}
apiVersion: v1
data:
  {{- (.Files.Glob "files/extra-pages/**.edn").AsConfig | nindent 2 }}
kind: ConfigMap
metadata:
  name:  {{ .Values.name | default "rems" }}-extra-pages
{{- end }}
